version: '3.9'
services:
    front:
        image: nginx:latest
        container_name: front
        ports:
            - "8080:80"
        volumes:
            - ./front:/usr/share/nginx/html


    back:
        image: node:latest
        container_name: back
        ports:
            - "3000:3000"
        volumes:
            - ./back:/my-app
        command: bash -c "cd /my-app && ls && npm i && node server.js"